-- INSERT INTO professional (name, speciality) VALUES ('Renato Marques da Silva', 'Spring Boot');
-- INSERT INTO professional (name, speciality) VALUES ('Monica Jose Correia', 'Java');
-- INSERT INTO professional (name, speciality) VALUES ('Maria Jose da Silva', 'MySQL');
-- INSERT INTO professional (name, speciality) VALUES ('Henrique Mendes da Silva', 'Testes');